<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Schema_definition
{
    public function get_required_schema()
    {
        return [
            'ipak_questions' => [
                'columns' => [
                    'id' => ['type' => 'INT UNSIGNED', 'auto_increment' => true, 'nullable' => false, 'primary' => true],
                    'question_code' => ['type' => 'VARCHAR(20)', 'nullable' => false, 'unique' => 'uq_ipak_question_code'],
                    'question_text' => ['type' => 'TEXT', 'nullable' => false],
                    'measurement_name' => ['type' => 'VARCHAR(100)', 'nullable' => false],
                    'category_name' => ['type' => 'VARCHAR(100)', 'nullable' => false],
                    'weight' => ['type' => 'DECIMAL(8,2)', 'nullable' => false, 'default' => '1.00'],
                    'sort_order' => ['type' => 'INT', 'nullable' => false, 'default' => '0'],
                    'is_active' => ['type' => 'TINYINT(1)', 'nullable' => false, 'default' => '1'],
                    'created_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP'],
                    'updated_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['id'], 'type' => 'PRIMARY'],
                    'uq_ipak_question_code' => ['columns' => ['question_code'], 'type' => 'UNIQUE'],
                ],
                'foreign_keys' => [],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
            'ipak_answer_options' => [
                'columns' => [
                    'id' => ['type' => 'INT UNSIGNED', 'auto_increment' => true, 'nullable' => false, 'primary' => true],
                    'question_id' => ['type' => 'INT UNSIGNED', 'nullable' => false],
                    'option_code' => ['type' => 'VARCHAR(10)', 'nullable' => false],
                    'option_label' => ['type' => 'VARCHAR(150)', 'nullable' => false],
                    'option_value' => ['type' => 'DECIMAL(8,2)', 'nullable' => false, 'default' => '0'],
                    'normalized_score' => ['type' => 'DECIMAL(6,2)', 'nullable' => false, 'default' => '0'],
                    'sort_order' => ['type' => 'INT', 'nullable' => false, 'default' => '0'],
                    'is_active' => ['type' => 'TINYINT(1)', 'nullable' => false, 'default' => '1'],
                    'created_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['id'], 'type' => 'PRIMARY'],
                    'uq_ipak_answer_option' => ['columns' => ['question_id', 'option_code'], 'type' => 'UNIQUE'],
                    'idx_ipak_option_question' => ['columns' => ['question_id'], 'type' => 'INDEX'],
                ],
                'foreign_keys' => [
                    'fk_ipak_option_question' => [
                        'columns' => ['question_id'],
                        'ref_table' => 'ipak_questions',
                        'ref_columns' => ['id'],
                        'on_update' => 'CASCADE',
                        'on_delete' => 'RESTRICT',
                    ],
                ],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
            'ipak_response_answers' => [
                'columns' => [
                    'id' => ['type' => 'BIGINT UNSIGNED', 'auto_increment' => true, 'nullable' => false, 'primary' => true],
                    'flex_response_id' => ['type' => 'BIGINT UNSIGNED', 'nullable' => true],
                    'kode' => ['type' => 'BIGINT UNSIGNED', 'nullable' => false],
                    'question_id' => ['type' => 'INT UNSIGNED', 'nullable' => false],
                    'option_id' => ['type' => 'INT UNSIGNED', 'nullable' => false],
                    'option_code_snapshot' => ['type' => 'VARCHAR(10)', 'nullable' => false],
                    'option_label_snapshot' => ['type' => 'VARCHAR(150)', 'nullable' => false],
                    'option_value_snapshot' => ['type' => 'DECIMAL(8,2)', 'nullable' => false],
                    'normalized_score_snapshot' => ['type' => 'DECIMAL(6,2)', 'nullable' => false],
                    'created_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['id'], 'type' => 'PRIMARY'],
                    'idx_ipak_answer_response' => ['columns' => ['kode'], 'type' => 'INDEX'],
                    'idx_ipak_answer_question' => ['columns' => ['question_id'], 'type' => 'INDEX'],
                    'idx_ipak_answer_flex' => ['columns' => ['flex_response_id'], 'type' => 'INDEX'],
                ],
                'foreign_keys' => [
                    'fk_ipak_answer_question' => [
                        'columns' => ['question_id'],
                        'ref_table' => 'ipak_questions',
                        'ref_columns' => ['id'],
                        'on_update' => 'CASCADE',
                        'on_delete' => 'RESTRICT',
                    ],
                    'fk_ipak_answer_option' => [
                        'columns' => ['option_id'],
                        'ref_table' => 'ipak_answer_options',
                        'ref_columns' => ['id'],
                        'on_update' => 'CASCADE',
                        'on_delete' => 'RESTRICT',
                    ],
                ],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
            'ipak_admin_roles' => [
                'columns' => [
                    'user_id' => ['type' => 'INT UNSIGNED', 'auto_increment' => false, 'nullable' => false, 'primary' => true],
                    'role_name' => ['type' => 'VARCHAR(50)', 'nullable' => false, 'unique' => 'uq_ipak_role_name'],
                    'description' => ['type' => 'VARCHAR(255)', 'nullable' => true],
                    'is_system' => ['type' => 'TINYINT(1)', 'nullable' => false, 'default' => '0'],
                    'created_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP'],
                    'updated_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['id'], 'type' => 'PRIMARY'],
                    'uq_ipak_role_name' => ['columns' => ['role_name'], 'type' => 'UNIQUE'],
                ],
                'foreign_keys' => [],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
            'ipak_surveys' => [
                'columns' => [
                    'id' => ['type' => 'INT UNSIGNED', 'auto_increment' => true, 'nullable' => false, 'primary' => true],
                    'survey_code' => ['type' => 'VARCHAR(30)', 'nullable' => false, 'unique' => 'uq_ipak_survey_code'],
                    'survey_name' => ['type' => 'VARCHAR(150)', 'nullable' => false],
                    'index_label' => ['type' => 'VARCHAR(60)', 'nullable' => false],
                    'description' => ['type' => 'TEXT', 'nullable' => true],
                    'color' => ['type' => 'VARCHAR(10)', 'nullable' => false, 'default' => "'#3049d8'"],
                    'is_active' => ['type' => 'TINYINT(1)', 'nullable' => false, 'default' => '1'],
                    'is_system_locked' => ['type' => 'TINYINT(1)', 'nullable' => false, 'default' => '0'],
                    'is_mandatory' => ['type' => 'TINYINT(1)', 'nullable' => false, 'default' => '0'],
                    'created_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP'],
                    'updated_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['id'], 'type' => 'PRIMARY'],
                    'uq_ipak_survey_code' => ['columns' => ['survey_code'], 'type' => 'UNIQUE'],
                    'idx_ipak_survey_active' => ['columns' => ['is_active', 'survey_name'], 'type' => 'INDEX'],
                ],
                'foreign_keys' => [],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
            'ipak_survey_questions' => [
                'columns' => [
                    'survey_id' => ['type' => 'INT UNSIGNED', 'nullable' => false, 'primary' => true],
                    'question_id' => ['type' => 'INT UNSIGNED', 'nullable' => false, 'primary' => true],
                    'sort_order' => ['type' => 'INT', 'nullable' => false, 'default' => '0'],
                    'weight_override' => ['type' => 'DECIMAL(8,2)', 'nullable' => true],
                    'is_required' => ['type' => 'TINYINT(1)', 'nullable' => false, 'default' => '1'],
                    'created_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['survey_id', 'question_id'], 'type' => 'PRIMARY'],
                    'idx_ipak_survey_question_order' => ['columns' => ['survey_id', 'sort_order'], 'type' => 'INDEX'],
                    'idx_ipak_question_surveys' => ['columns' => ['question_id', 'survey_id'], 'type' => 'INDEX'],
                ],
                'foreign_keys' => [
                    'fk_ipak_sq_survey' => [
                        'columns' => ['survey_id'],
                        'ref_table' => 'ipak_surveys',
                        'ref_columns' => ['id'],
                        'on_update' => 'CASCADE',
                        'on_delete' => 'CASCADE',
                    ],
                    'fk_ipak_sq_question' => [
                        'columns' => ['question_id'],
                        'ref_table' => 'ipak_questions',
                        'ref_columns' => ['id'],
                        'on_update' => 'CASCADE',
                        'on_delete' => 'RESTRICT',
                    ],
                ],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
            'ipak_survey_score_categories' => [
                'columns' => [
                    'id' => ['type' => 'INT UNSIGNED', 'auto_increment' => true, 'nullable' => false, 'primary' => true],
                    'survey_id' => ['type' => 'INT UNSIGNED', 'nullable' => false],
                    'category_label' => ['type' => 'VARCHAR(80)', 'nullable' => false],
                    'minimum_score' => ['type' => 'DECIMAL(6,2)', 'nullable' => false],
                    'maximum_score' => ['type' => 'DECIMAL(6,2)', 'nullable' => false],
                    'color' => ['type' => 'VARCHAR(10)', 'nullable' => false, 'default' => "'#64748b'"],
                    'sort_order' => ['type' => 'INT', 'nullable' => false, 'default' => '0'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['id'], 'type' => 'PRIMARY'],
                    'uq_ipak_survey_category_range' => ['columns' => ['survey_id', 'minimum_score', 'maximum_score'], 'type' => 'UNIQUE'],
                ],
                'foreign_keys' => [
                    'fk_ipak_category_survey' => [
                        'columns' => ['survey_id'],
                        'ref_table' => 'ipak_surveys',
                        'ref_columns' => ['id'],
                        'on_update' => 'CASCADE',
                        'on_delete' => 'CASCADE',
                    ],
                ],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
            'ipak_forms' => [
                'columns' => [
                    'id' => ['type' => 'INT UNSIGNED', 'auto_increment' => true, 'nullable' => false, 'primary' => true],
                    'form_code' => ['type' => 'VARCHAR(30)', 'nullable' => false, 'unique' => 'uq_ipak_form_code'],
                    'form_name' => ['type' => 'VARCHAR(150)', 'nullable' => false],
                    'description' => ['type' => 'TEXT', 'nullable' => true],
                    'is_default' => ['type' => 'TINYINT(1)', 'nullable' => false, 'default' => '0'],
                    'is_active' => ['type' => 'TINYINT(1)', 'nullable' => false, 'default' => '1'],
                    'is_public_listed' => ['type' => 'TINYINT(1)', 'nullable' => false, 'default' => '1'],
                    'created_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP'],
                    'updated_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['id'], 'type' => 'PRIMARY'],
                    'uq_ipak_form_code' => ['columns' => ['form_code'], 'type' => 'UNIQUE'],
                    'idx_ipak_form_default' => ['columns' => ['is_active', 'is_default'], 'type' => 'INDEX'],
                ],
                'foreign_keys' => [],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
            'ipak_form_surveys' => [
                'columns' => [
                    'form_id' => ['type' => 'INT UNSIGNED', 'nullable' => false, 'primary' => true],
                    'survey_id' => ['type' => 'INT UNSIGNED', 'nullable' => false, 'primary' => true],
                    'sort_order' => ['type' => 'INT', 'nullable' => false, 'default' => '0'],
                    'section_label' => ['type' => 'VARCHAR(150)', 'nullable' => true],
                    'created_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['form_id', 'survey_id'], 'type' => 'PRIMARY'],
                    'idx_ipak_form_survey_order' => ['columns' => ['form_id', 'sort_order'], 'type' => 'INDEX'],
                ],
                'foreign_keys' => [
                    'fk_ipak_fs_form' => [
                        'columns' => ['form_id'],
                        'ref_table' => 'ipak_forms',
                        'ref_columns' => ['id'],
                        'on_update' => 'CASCADE',
                        'on_delete' => 'CASCADE',
                    ],
                    'fk_ipak_fs_survey' => [
                        'columns' => ['survey_id'],
                        'ref_table' => 'ipak_surveys',
                        'ref_columns' => ['id'],
                        'on_update' => 'CASCADE',
                        'on_delete' => 'RESTRICT',
                    ],
                ],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
            'ipak_submission_surveys' => [
                'columns' => [
                    'id' => ['type' => 'BIGINT UNSIGNED', 'auto_increment' => true, 'nullable' => false, 'primary' => true],
                    'skm_data_id' => ['type' => 'INT(10)', 'nullable' => false],
                    'form_id' => ['type' => 'INT UNSIGNED', 'nullable' => false],
                    'survey_id' => ['type' => 'INT UNSIGNED', 'nullable' => false],
                    'flex_response_id' => ['type' => 'BIGINT UNSIGNED', 'nullable' => true],
                    'score' => ['type' => 'DECIMAL(6,2)', 'nullable' => false],
                    'category_label' => ['type' => 'VARCHAR(80)', 'nullable' => false],
                    'answer_count' => ['type' => 'INT', 'nullable' => false, 'default' => '0'],
                    'weight_total' => ['type' => 'DECIMAL(10,2)', 'nullable' => false, 'default' => '0'],
                    'created_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['id'], 'type' => 'PRIMARY'],
                    'uq_ipak_submission_survey' => ['columns' => ['skm_data_id', 'survey_id'], 'type' => 'UNIQUE'],
                    'idx_ipak_result_survey_score' => ['columns' => ['survey_id', 'score'], 'type' => 'INDEX'],
                    'idx_ipak_result_form' => ['columns' => ['form_id'], 'type' => 'INDEX'],
                ],
                'foreign_keys' => [
                    'fk_ipak_result_skm' => [
                        'columns' => ['skm_data_id'],
                        'ref_table' => 'skm_data_skm',
                        'ref_columns' => ['kode'],
                        'on_update' => 'CASCADE',
                        'on_delete' => 'CASCADE',
                    ],
                    'fk_ipak_result_form' => [
                        'columns' => ['form_id'],
                        'ref_table' => 'ipak_forms',
                        'ref_columns' => ['id'],
                        'on_update' => 'CASCADE',
                        'on_delete' => 'RESTRICT',
                    ],
                    'fk_ipak_result_survey' => [
                        'columns' => ['survey_id'],
                        'ref_table' => 'ipak_surveys',
                        'ref_columns' => ['id'],
                        'on_update' => 'CASCADE',
                        'on_delete' => 'RESTRICT',
                    ],
                ],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
            'ipak_submission_survey_answers' => [
                'columns' => [
                    'survey_result_id' => ['type' => 'BIGINT UNSIGNED', 'nullable' => false, 'primary' => true],
                    'response_answer_id' => ['type' => 'BIGINT UNSIGNED', 'nullable' => false, 'primary' => true],
                    'applied_weight' => ['type' => 'DECIMAL(8,2)', 'nullable' => false, 'default' => '1.00'],
                    'created_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['survey_result_id', 'response_answer_id'], 'type' => 'PRIMARY'],
                    'idx_ipak_result_answer' => ['columns' => ['response_answer_id'], 'type' => 'INDEX'],
                ],
                'foreign_keys' => [
                    'fk_ipak_result_answer_result' => [
                        'columns' => ['survey_result_id'],
                        'ref_table' => 'ipak_submission_surveys',
                        'ref_columns' => ['id'],
                        'on_update' => 'CASCADE',
                        'on_delete' => 'CASCADE',
                    ],
                    'fk_ipak_result_answer_detail' => [
                        'columns' => ['response_answer_id'],
                        'ref_table' => 'ipak_response_answers',
                        'ref_columns' => ['id'],
                        'on_update' => 'CASCADE',
                        'on_delete' => 'CASCADE',
                    ],
                ],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
            'ipak_form_fields' => [
                'columns' => [
                    'form_id' => ['type' => 'INT UNSIGNED', 'nullable' => false, 'primary' => true],
                    'field_key' => ['type' => 'VARCHAR(30)', 'nullable' => false, 'primary' => true],
                    'field_label' => ['type' => 'VARCHAR(100)', 'nullable' => false],
                    'field_mode' => ['type' => "ENUM('hidden','optional','required')", 'nullable' => false, 'default' => 'hidden'],
                    'help_text' => ['type' => 'VARCHAR(255)', 'nullable' => true],
                    'field_group' => ['type' => "ENUM('access','identity')", 'nullable' => false, 'default' => 'identity'],
                    'field_type' => ['type' => 'VARCHAR(20)', 'nullable' => false, 'default' => 'text'],
                    'field_options' => ['type' => 'TEXT', 'nullable' => true],
                    'sort_order' => ['type' => 'INT', 'nullable' => false, 'default' => '0'],
                    'is_system' => ['type' => 'TINYINT(1)', 'nullable' => false, 'default' => '1'],
                    'updated_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['form_id', 'field_key'], 'type' => 'PRIMARY'],
                    'idx_ipak_form_field_mode' => ['columns' => ['field_key', 'field_mode'], 'type' => 'INDEX'],
                ],
                'foreign_keys' => [
                    'fk_ipak_form_field_form' => [
                        'columns' => ['form_id'],
                        'ref_table' => 'ipak_forms',
                        'ref_columns' => ['id'],
                        'on_update' => 'CASCADE',
                        'on_delete' => 'CASCADE',
                    ],
                ],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
            'ipak_response_fields' => [
                'columns' => [
                    'kode' => ['type' => 'BIGINT UNSIGNED', 'nullable' => false, 'primary' => true],
                    'flex_response_id' => ['type' => 'BIGINT UNSIGNED', 'nullable' => true],
                    'field_key' => ['type' => 'VARCHAR(30)', 'nullable' => false, 'primary' => true],
                    'field_label_snapshot' => ['type' => 'VARCHAR(100)', 'nullable' => false],
                    'field_value' => ['type' => 'TEXT', 'nullable' => false],
                    'field_mode_snapshot' => ['type' => "ENUM('hidden','optional','required')", 'nullable' => false, 'default' => 'hidden'],
                    'field_group_snapshot' => ['type' => "ENUM('access','identity')", 'nullable' => false, 'default' => 'identity'],
                    'field_type_snapshot' => ['type' => 'VARCHAR(20)', 'nullable' => false, 'default' => 'text'],
                    'field_options_snapshot' => ['type' => 'TEXT', 'nullable' => true],
                    'sort_order_snapshot' => ['type' => 'INT', 'nullable' => false, 'default' => '0'],
                    'created_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['kode', 'field_key'], 'type' => 'PRIMARY'],
                ],
                'foreign_keys' => [],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
            'ipak_survey_responses' => [
                'columns' => [
                    'kode' => ['type' => 'BIGINT UNSIGNED', 'nullable' => false, 'primary' => true],
                    'form_code' => ['type' => 'VARCHAR(30)', 'nullable' => false],
                    'survey_type' => ['type' => "ENUM('SKM','SURVEY')", 'nullable' => false, 'default' => 'SKM'],
                    'response_source' => ['type' => "ENUM('SKM','FLEX')", 'nullable' => false, 'default' => 'SKM'],
                    'created_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['kode'], 'type' => 'PRIMARY'],
                    'idx_ipak_flex_form' => ['columns' => ['form_code'], 'type' => 'INDEX'],
                    'idx_ipak_flex_type' => ['columns' => ['survey_type'], 'type' => 'INDEX'],
                ],
                'foreign_keys' => [],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
            'ipak_api_clients' => [
                'columns' => [
                    'id' => ['type' => 'INT UNSIGNED', 'auto_increment' => true, 'nullable' => false, 'primary' => true],
                    'client_name' => ['type' => 'VARCHAR(120)', 'nullable' => false],
                    'client_code' => ['type' => 'VARCHAR(50)', 'nullable' => false, 'unique' => 'uq_ipak_api_client_code'],
                    'description' => ['type' => 'VARCHAR(255)', 'nullable' => true],
                    'survey_scope' => ['type' => "ENUM('all','selected')", 'nullable' => false, 'default' => 'selected'],
                    'allowed_survey_ids' => ['type' => 'JSON', 'nullable' => false],
                    'allowed_resources' => ['type' => 'JSON', 'nullable' => false],
                    'allowed_dimensions' => ['type' => 'JSON', 'nullable' => false],
                    'allowed_detail_fields' => ['type' => 'JSON', 'nullable' => false],
                    'max_page_size' => ['type' => 'INT', 'nullable' => false, 'default' => '50'],
                    'rate_limit_per_minute' => ['type' => 'INT', 'nullable' => false, 'default' => '60'],
                    'allowed_ip_addresses' => ['type' => 'VARCHAR(2000)', 'nullable' => false, 'default' => "''"],
                    'allowed_origin' => ['type' => 'VARCHAR(255)', 'nullable' => false, 'default' => "''"],
                    'expires_at' => ['type' => 'DATETIME', 'nullable' => true],
                    'is_active' => ['type' => 'TINYINT(1)', 'nullable' => false, 'default' => '1'],
                    'created_by' => ['type' => 'INT UNSIGNED', 'nullable' => false],
                    'created_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP'],
                    'updated_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['id'], 'type' => 'PRIMARY'],
                    'uq_ipak_api_client_code' => ['columns' => ['client_code'], 'type' => 'UNIQUE'],
                    'idx_ipak_api_client_active' => ['columns' => ['is_active'], 'type' => 'INDEX'],
                ],
                'foreign_keys' => [],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
            'ipak_api_access_logs' => [
                'columns' => [
                    'id' => ['type' => 'BIGINT UNSIGNED', 'auto_increment' => true, 'nullable' => false, 'primary' => true],
                    'client_id' => ['type' => 'INT UNSIGNED', 'nullable' => false],
                    'endpoint' => ['type' => 'VARCHAR(255)', 'nullable' => false],
                    'method' => ['type' => 'VARCHAR(10)', 'nullable' => false],
                    'request_ip' => ['type' => 'VARCHAR(45)', 'nullable' => false],
                    'request_origin' => ['type' => 'VARCHAR(255)', 'nullable' => true],
                    'response_status' => ['type' => 'INT', 'nullable' => false],
                    'response_time_ms' => ['type' => 'INT', 'nullable' => false],
                    'request_params' => ['type' => 'JSON', 'nullable' => true],
                    'error_message' => ['type' => 'TEXT', 'nullable' => true],
                    'created_at' => ['type' => 'DATETIME', 'nullable' => false, 'default' => 'CURRENT_TIMESTAMP'],
                ],
                'indexes' => [
                    'PRIMARY' => ['columns' => ['id'], 'type' => 'PRIMARY'],
                    'idx_ipak_api_log_client' => ['columns' => ['client_id', 'created_at'], 'type' => 'INDEX'],
                    'idx_ipak_api_log_status' => ['columns' => ['response_status'], 'type' => 'INDEX'],
                ],
                'foreign_keys' => [
                    'fk_ipak_api_log_client' => [
                        'columns' => ['client_id'],
                        'ref_table' => 'ipak_api_clients',
                        'ref_columns' => ['id'],
                        'on_update' => 'CASCADE',
                        'on_delete' => 'CASCADE',
                    ],
                ],
                'engine' => 'InnoDB',
                'charset' => 'utf8',
                'collate' => 'utf8_general_ci',
            ],
        ];
    }
}