-- Data bawaan perangkat daerah. Tidak mengubah struktur tabel yang sudah ada.
UPDATE trunitkerja
SET n_unitkerja = 'DINAS KOMUNIKASI DAN INFORMATIKA PROVINSI JAWA BARAT'
WHERE n_unitkerja IN (
    'DINAS KOMUNIKASI DAN INFORMASI PROVINSI JAWA BARAT',
    'DINAS KOMUNIKASI DAN INFORMATIKA'
);

INSERT INTO trunitkerja (n_unitkerja, nm_cap)
SELECT
    'DINAS PENANAMAN MODAL DAN PELAYANAN TERPADU SATU PINTU PROVINSI JAWA BARAT',
    ''
WHERE NOT EXISTS (
    SELECT 1
    FROM trunitkerja
    WHERE n_unitkerja = 'DINAS PENANAMAN MODAL DAN PELAYANAN TERPADU SATU PINTU PROVINSI JAWA BARAT'
);

INSERT INTO trunitkerja (n_unitkerja, nm_cap)
SELECT
    'DINAS KOMUNIKASI DAN INFORMATIKA PROVINSI JAWA BARAT',
    ''
WHERE NOT EXISTS (
    SELECT 1
    FROM trunitkerja
    WHERE n_unitkerja = 'DINAS KOMUNIKASI DAN INFORMATIKA PROVINSI JAWA BARAT'
);
