<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$route['default_controller'] = 'survey/dashboard';
$route['404_override'] = '';
$route['translate_uri_dashes'] = FALSE;

$route['dashboard'] = 'survey/dashboard';
$route['surveys'] = 'survey/catalog';
$route['survei/pilih'] = 'survey/catalog';
$route['survey'] = 'survey/index';
$route['survei'] = 'survey/index';
$route['skm/Survei.php'] = 'survey/index';
$route['survey/submit']['post'] = 'survey/submit';
$route['survey/success/(:any)'] = 'survey/success/$1';
$route['api/v1/survey-data/(:any)'] = 'api/survey_data/$1';

$route['admin'] = 'admin/index';
$route['admin/login'] = 'admin/login';
$route['admin/logout'] = 'admin/logout';
$route['admin/dashboard'] = 'admin/dashboard';
$route['admin/responses'] = 'admin/responses';
$route['admin/responses/(:any)'] = 'admin/detail/$1';
$route['admin/export'] = 'admin/export';
$route['admin/questions'] = 'admin/questions';
$route['admin/questions/create'] = 'admin/create_question';
$route['admin/surveys'] = 'admin/surveys';
$route['admin/delete-survey/(:num)']['post'] = 'admin/delete_survey/$1';
$route['admin/forms'] = 'admin/forms';
$route['admin/forms/create'] = 'admin/create_form';
$route['admin/forms/edit/(:num)'] = 'admin/edit_form/$1';
$route['admin/kbli'] = 'admin/kbli';
$route['admin/kbli/edit/(:num)'] = 'admin/edit_kbli/$1';
$route['admin/kbli/delete/(:num)']['post'] = 'admin/delete_kbli/$1';
$route['admin/api-builder'] = 'admin/api_builder';
$route['admin/api-builder/create'] = 'admin/api_client_form';
$route['admin/api-builder/edit/(:num)'] = 'admin/api_client_form/$1';
$route['admin/api-builder/toggle/(:num)']['post'] = 'admin/api_client_toggle/$1';
$route['admin/api-builder/regenerate/(:num)']['post'] = 'admin/api_client_regenerate/$1';
$route['admin/api-builder/documentation/(:num)'] = 'admin/api_client_documentation/$1';
$route['admin/kbli'] = 'admin/kbli';
$route['admin/kbli/edit/(:num)'] = 'admin/edit_kbli/$1';
$route['admin/kbli/delete/(:num)']['post'] = 'admin/delete_kbli/$1';
$route['admin/units'] = 'admin/units';
$route['admin/help'] = 'admin/help';
$route['admin/sync-database'] = 'admin/sync_database';
$route['admin/users'] = 'admin/users';
$route['admin/users/create'] = 'admin/create_user';
$route['admin/users/edit/(:num)'] = 'admin/edit_user/$1';
$route['admin/users/delete/(:num)']['post'] = 'admin/delete_user/$1';
$route['admin/profile'] = 'admin/profile';
$route['admin/change-password']['post'] = 'admin/change_password';
